//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CafeRestaurantEntities : DbContext
    {
        public CafeRestaurantEntities()
            : base("name=CafeRestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ban> Ban { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<LoaiNuoc> LoaiNuoc { get; set; }
        public virtual DbSet<SuKien> SuKien { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<ThucUong> ThucUong { get; set; }
    
        public virtual int usp_ThemBan(string maBan, string maTang, string tenBan, Nullable<byte> trangThai)
        {
            var maBanParameter = maBan != null ?
                new ObjectParameter("MaBan", maBan) :
                new ObjectParameter("MaBan", typeof(string));
    
            var maTangParameter = maTang != null ?
                new ObjectParameter("MaTang", maTang) :
                new ObjectParameter("MaTang", typeof(string));
    
            var tenBanParameter = tenBan != null ?
                new ObjectParameter("TenBan", tenBan) :
                new ObjectParameter("TenBan", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemBan", maBanParameter, maTangParameter, tenBanParameter, trangThaiParameter);
        }
    
        public virtual int usp_ThemDonHang(string maDonHang, string maThucUong, string maLoai, Nullable<byte> soLuong, string maHD)
        {
            var maDonHangParameter = maDonHang != null ?
                new ObjectParameter("MaDonHang", maDonHang) :
                new ObjectParameter("MaDonHang", typeof(string));
    
            var maThucUongParameter = maThucUong != null ?
                new ObjectParameter("MaThucUong", maThucUong) :
                new ObjectParameter("MaThucUong", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(byte));
    
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemDonHang", maDonHangParameter, maThucUongParameter, maLoaiParameter, soLuongParameter, maHDParameter);
        }
    
        public virtual int usp_ThemHoaDon(string maHD, Nullable<System.DateTime> ngayHD, string maNV, string maBan, string maTang, Nullable<int> tongTien, string maSuKien, Nullable<int> duaTruoc, Nullable<int> conLai)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var ngayHDParameter = ngayHD.HasValue ?
                new ObjectParameter("NgayHD", ngayHD) :
                new ObjectParameter("NgayHD", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maBanParameter = maBan != null ?
                new ObjectParameter("MaBan", maBan) :
                new ObjectParameter("MaBan", typeof(string));
    
            var maTangParameter = maTang != null ?
                new ObjectParameter("MaTang", maTang) :
                new ObjectParameter("MaTang", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(int));
    
            var maSuKienParameter = maSuKien != null ?
                new ObjectParameter("MaSuKien", maSuKien) :
                new ObjectParameter("MaSuKien", typeof(string));
    
            var duaTruocParameter = duaTruoc.HasValue ?
                new ObjectParameter("DuaTruoc", duaTruoc) :
                new ObjectParameter("DuaTruoc", typeof(int));
    
            var conLaiParameter = conLai.HasValue ?
                new ObjectParameter("ConLai", conLai) :
                new ObjectParameter("ConLai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemHoaDon", maHDParameter, ngayHDParameter, maNVParameter, maBanParameter, maTangParameter, tongTienParameter, maSuKienParameter, duaTruocParameter, conLaiParameter);
        }
    
        public virtual int usp_ThemLoaiNuoc(string maLoai, string tenLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemLoaiNuoc", maLoaiParameter, tenLoaiParameter);
        }
    
        public virtual int usp_ThemSuKien(string maSuKien, string tenSuKien, Nullable<byte> tyLeGiam, Nullable<short> soLuong, Nullable<System.DateTime> thoiGian_BD, Nullable<System.DateTime> thoiGian_KT)
        {
            var maSuKienParameter = maSuKien != null ?
                new ObjectParameter("MaSuKien", maSuKien) :
                new ObjectParameter("MaSuKien", typeof(string));
    
            var tenSuKienParameter = tenSuKien != null ?
                new ObjectParameter("TenSuKien", tenSuKien) :
                new ObjectParameter("TenSuKien", typeof(string));
    
            var tyLeGiamParameter = tyLeGiam.HasValue ?
                new ObjectParameter("TyLeGiam", tyLeGiam) :
                new ObjectParameter("TyLeGiam", typeof(byte));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(short));
    
            var thoiGian_BDParameter = thoiGian_BD.HasValue ?
                new ObjectParameter("ThoiGian_BD", thoiGian_BD) :
                new ObjectParameter("ThoiGian_BD", typeof(System.DateTime));
    
            var thoiGian_KTParameter = thoiGian_KT.HasValue ?
                new ObjectParameter("ThoiGian_KT", thoiGian_KT) :
                new ObjectParameter("ThoiGian_KT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemSuKien", maSuKienParameter, tenSuKienParameter, tyLeGiamParameter, soLuongParameter, thoiGian_BDParameter, thoiGian_KTParameter);
        }
    
        public virtual int usp_ThemTaiKhoan(string tenDangNhap, string hoTen, string matKhau, Nullable<bool> loaiTaiKhoan, string cMND, Nullable<System.DateTime> ngaySinh, string soDT, Nullable<bool> conLam)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var loaiTaiKhoanParameter = loaiTaiKhoan.HasValue ?
                new ObjectParameter("LoaiTaiKhoan", loaiTaiKhoan) :
                new ObjectParameter("LoaiTaiKhoan", typeof(bool));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var soDTParameter = soDT != null ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(string));
    
            var conLamParameter = conLam.HasValue ?
                new ObjectParameter("ConLam", conLam) :
                new ObjectParameter("ConLam", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemTaiKhoan", tenDangNhapParameter, hoTenParameter, matKhauParameter, loaiTaiKhoanParameter, cMNDParameter, ngaySinhParameter, soDTParameter, conLamParameter);
        }
    
        public virtual int usp_ThemThucUong(string maThucUong, string maLoai, string tenThucUong, Nullable<decimal> donGia, Nullable<bool> khaDung)
        {
            var maThucUongParameter = maThucUong != null ?
                new ObjectParameter("MaThucUong", maThucUong) :
                new ObjectParameter("MaThucUong", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenThucUongParameter = tenThucUong != null ?
                new ObjectParameter("TenThucUong", tenThucUong) :
                new ObjectParameter("TenThucUong", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var khaDungParameter = khaDung.HasValue ?
                new ObjectParameter("KhaDung", khaDung) :
                new ObjectParameter("KhaDung", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemThucUong", maThucUongParameter, maLoaiParameter, tenThucUongParameter, donGiaParameter, khaDungParameter);
        }
    }
}
