//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public string MaDonHang { get; set; }
        public string MaThucUong { get; set; }
        public string MaLoai { get; set; }
        public byte SoLuong { get; set; }
        public string MaHD { get; set; }
    
        public virtual ThucUong ThucUong { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
