//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.DonHang = new HashSet<DonHang>();
        }
    
        public string MaHD { get; set; }
        public System.DateTime NgayHD { get; set; }
        public string MaNV { get; set; }
        public string MaBan { get; set; }
        public string MaTang { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string MaSuKien { get; set; }
        public Nullable<int> DuaTruoc { get; set; }
        public Nullable<int> ConLai { get; set; }
    
        public virtual Ban Ban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual SuKien SuKien { get; set; }
    }
}
