//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe
{
	using System;
	using System.Collections.Generic;

	public partial class SuKien
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public SuKien()
		{
			this.HoaDon = new HashSet<HoaDon>();
		}

		public string MaSuKien { get; set; }
		public string TenSuKien { get; set; }
		public Nullable<byte> TyLeGiam { get; set; }
		public Nullable<short> SoLuong { get; set; }
		public Nullable<System.DateTime> ThoiGian_BD { get; set; }
		public Nullable<System.DateTime> ThoiGian_KT { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<HoaDon> HoaDon { get; set; }
	}
}
