//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public string TenDangNhap { get; set; }
        public string HoTen { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> LoaiTaiKhoan { get; set; }
        public string CMND { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SoDT { get; set; }
        public Nullable<bool> ConLam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}
